### ISSUE TITLE
Plex Player not loading show data

### ISSUE THREAD

**Issue by adamus1red** [plexinc/plex-media-player#1014]
### Test environment

**PMS Version: 1.21.4.4054**
**PMP Version: 1.28.0.1681-cc6e807c**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel): Windows**

### Steps to reproduce
1. Browse into TV library
2. wait 5-15 minutes

### Current behavior
1. Plex player sits with a loading spinner forever
2. No show/episode information is displayed

### Expected behavior
1. Player loads up the show/episode information and displays it correctly

### PMP Log
https://pastebin.com/2k0WAsFd

**Comment by egoebelbecker** [comment]
Seen this on Mac. Recent update seemed to fix it for a few days, now it's back.

**Comment by ozsmac** [comment]
I'm having exactly the same issue myself, when navigating through the show level, into season, I just see the spinning circle.  If I exit the app, it will work for a short time (5-10 minutes) and then return to the same issue, orange spinning circle.  Here is a link to the forums post that I've placed about this issue.

https://forums.plex.tv/t/pmp-macos-bug-spinning-circle-when-viewing-seasons-of-a-show/696459

**Comment by mseeley** [comment]
We haven't been able to identify cause for this issue.

The builds below are alpha builds from our 1.29.0 release candidate. We don't expect them to bite but these are alpha builds so expect the unexpected. 🥃 

Will any of you please try running 1.29.0 and let us know if the issue repeats for you? If it does, will you please provide the `Plex.log` file [1]?

- [Windows (Windows 10 or later (64-bit only).)](https://artifacts.plex.tv/plex-desktop-alpha/1.29.0.1840-08e4904b/windows/Plex-1.29.0.1840-08e4904b-x86_64.exe)
- [MacOS (10.13 High Sierra or later (64-bit only).)](https://artifacts.plex.tv/plex-desktop-alpha/1.29.0.1840-08e4904b/macos/Plex-1.29.0.1840-08e4904b-x86_64.zip)

[1] Windows: `%LOCALAPPDATA%\Plex\Logs\`, Mac: `~/Library/Logs/Plex/`

**Comment by egoebelbecker** [comment]
Thanks for this. 

I'll run this tomorrow during the day when I usually watch few shows on my laptop.

**Comment by Lothian1** [comment]
I had a try with the alpha version Plex-1.29.0.1840-08e4904b-x86_64. I thought it was going great but then the problem came back. By the way, if I create a new server and run it, everything works well for a while but after I get all my filles loaded and previews generated, the problem seems to come back. I am now tryying to work out what it is in my library that is causing the difficulty by a process of elimination.

Here are the server logs and thelogs from the client. I could not upload the databse... Too large
[Client Logs.zip](https://github.com/plexinc/plex-media-player/files/6080629/Client.Logs.zip)
[Plex Media Server Logs_2021-03-03_23-01-10.zip](https://github.com/plexinc/plex-media-player/files/6080630/Plex.Media.Server.Logs_2021-03-03_23-01-10.zip)

**Comment by adamus1red** [comment]
Issue presents on the windows version as well.

**Comment by egoebelbecker** [comment]
Didn't take long to happen again this morning with the new build. (Note that my server is running UTC and my desktop is EST. Never got around to change the TZ on the server.)


[Plex Media Server Logs_2021-03-04_14-00-37.zip](https://github.com/plexinc/plex-media-player/files/6084167/Plex.Media.Server.Logs_2021-03-04_14-00-37.zip)
[Plex.log](https://github.com/plexinc/plex-media-player/files/6084169/Plex.log)

**Comment by ozsmac** [comment]
Within 40 minutes of testing I also saw the issue reoccur.  Will upload plex.log when I’m back in front of my machine.

**Comment by mseeley** [comment]
Thanks everyone for the feedback + logs. I'm investigating more today. The way the bug appears solved then strikes must be a hint at its origin. 🍀 🤞

**Comment by Dork74** [comment]
Just tried this Windows version and I still have the issue.  It appears that everything is OK until I add new content to the server and then scan library (I don't have auto or timed scanning turned on). I noticed this behavior on the earlier versions, but didn't update the forum site yet. I wanted to try this version first. I can upload logs if you want.

**Comment by mseeley** [comment]
Hi @Dork74 that's a great hint, lines up with one of our ideas too. Uploading the `Plex.log` when you see it is always appreciated. 👍

**Comment by Dork74** [comment]
Glad it might help. I did some testing yesterday with the other versions
based on a hunch.

I actually just did some more playing around and scanning the library,
without adding anything to the library, produces the behavior. However, it
seems to return to normal with a player restart.  I don't think the issue
was resolved with a restart in the other versions, but I generally went
back to 1,25 as soon as I saw it happen at least in 1.28.  I can
specifically check the other versions if you want.  I have attached the
plex.log while it was displaying the behavior.

Thanks
Jeff

**Comment by Dork74** [comment]
CORRECTION:  It only temporarily functions normally on restart. As other have noted it does return after running for awhile (<30 minutes)

**Comment by mseeley** [comment]
@adamus1red, @egoebelbecker, @Lothian1, @ozsmac, @Dork74 here's a new 1.29 alpha build. Will you please kick the tires once more? If you see it again will you please reply+attach the `Plex.log` file [1]?

* [Windows (Windows 10 or later (64-bit only).)](https://artifacts.plex.tv/plex-desktop-alpha/1.29.0.1860-6f413198/windows/Plex-1.29.0.1860-6f413198-x86_64.exe)
* [MacOS (10.13 High Sierra or later (64-bit only).)](https://artifacts.plex.tv/plex-desktop-alpha/1.29.0.1860-6f413198/macos/Plex-1.29.0.1860-6f413198-x86_64.zip)

I've been unable to reproduce the problem over many attempts. I addressed several issues based on log file hints. I can't claim any have fixed the issue but stranger things have happened.

Thank you all for your help. ❤️ 

[1] Windows: %LOCALAPPDATA%\Plex\Logs\, Mac: ~/Library/Logs/Plex/

**Comment by ozsmac** [comment]
Thanks @mseeley, installed the new Alpha (1.29.0.1860-6f413198) and will test it today.

**Comment by adamus1red** [comment]
@mseeley the Windows alpha doesn't display a UI at all.
![image](https://user-images.githubusercontent.com/2502582/110397403-b5813f80-8069-11eb-8b61-28c352c4e8e6.png)

**Comment by mseeley** [comment]
Thanks @adamus1red. On it.

**Comment by mseeley** [comment]
I can reproduce here on the Windows build, the macOS build is fine. Perplexing in all the wrong sort of ways. :(

Investigating.

**Comment by mseeley** [comment]
1.29.0.1861-f78777aa alpha build for testing. This correct for the black screen issue. Thanks for catching that @adamus1red sorry it slipped in.

* [Windows (Windows 10 or later (64-bit only).)](https://artifacts.plex.tv/plex-desktop-alpha/1.29.0.1861-f78777aa/windows/Plex-1.29.0.1861-f78777aa-x86_64.exe)
* [MacOS (10.13 High Sierra or later (64-bit only).)](https://artifacts.plex.tv/plex-desktop-alpha/1.29.0.1861-f78777aa/macos/Plex-1.29.0.1861-f78777aa-x86_64.zip)

**Comment by ozsmac** [comment]
@mseeley have been testing v1.29.0.1860-6f413198 on two MacBook Pro's for the last few hours.  Haven't seen the issue re-occur just yet.

I will update to build 1861 and let you know how things go.  Fingers crossed, this has somehow fixed it.

**Comment by egoebelbecker** [comment]
Based on a quick look, it's fixed. I added a few files to my library and it's still letting me see details on shows. I'll kick the doors and slam the tires a bit more tomorrow.

**Comment by Dork74** [comment]
@mseeley  Been running 1.29.0.1861-f78777aa for an hour or so on Windows and seems to be fine. Scanned libraries and added content with no problem so far.  I will continue to run it and tomorrow will also check it on a second machine.

**Comment by ozsmac** [comment]
@mseeley good news, now been running on two machines, testing every hour or so, all fixed with 1861. Thank you for the prompt response and quick fix.

**Comment by Dork74** [comment]
@mseeley Looks like you fixed it, thanks! Note that I just updated the server to 1.22.0.4163 and no problems.

**Comment by Lothian1** [comment]
Looks like you fixed it... After the blank screen version,  I installed the old one again to prove the problem still existed and was able to expose the problem. Then I installed this new versin and even after several hours of viewing, the problem seems to be gone.

Thanks for taking this problem seriously when it was so hard to reproduce. It would have been easy to believe that we had corrupt servres or some other user error and ignore it. That is excellent customer service and part of the reason I am very happy with my Plex subscription.

**Comment by mseeley** [comment]
Thanks everyone for your patience and testing help. We've included these changes in our 1.29.0 release. More information is available:

- https://forums.plex.tv/t/plex-for-mac-and-windows/446435/41?u=mattseeley
- https://forums.plex.tv/t/cant-access-tv-shows-using-plex-for-windows-1-27-2-1599/687174/35?u=mattseeley.
