### ISSUE TITLE
'Micro-stuttering' every time i use the Win10 PMP

### ISSUE THREAD

**Issue by Jako4460** [plexinc/plex-media-player#1022]
### Test environment

**PMS Version:** 1.22.2.4282-a97b03fad 
**PMP Version:** 1.30.1.2115-81e1fc3f
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows 10 / Windows 10

### Steps to reproduce
1. When using the PMP on my new windows laptop i experience small 'micro-stuttering', where a single frame freezes in a split second so the playback doesn't seem smooth. It does not occur that much, maybe between 2-10 times in each 50min episode i watch. I have experinces the issue every time i have used the PMP, also when the content was downloaded. I have tried recreating the issue with the attached logs. I played the epsiode (locally, not downloaded) until i first encountered stuttering, then i disabled hardware decodiing and played again until another stuttering occured, then i enabled the hardware decoding again. So in the recreation the stuttering only occured twice, i have no problems however when i use the web player. I have tried installing severel versions of the PMP

Seems like some people in this thread have a similar issue:
https://forums.plex.tv/t/plex-for-windows-is-stuttering-in-direct-play/594504/9

### Current behavior
1.  I experince small 'micro-stuttering' at every playback in PMP.

### Expected behavior
1. The 'micro-stuttering' ruins the experince. 

I really enjoy your work.
Best regards / Jakob 
[PlexLogs.zip](https://github.com/plexinc/plex-media-player/files/6306777/PlexLogs.zip)

**Comment by mseeley** [comment]
Hi @Jako4460. We believe this has been addressed in our 1.31 release currently undergoing testing. Although it's scheduled to release on Thursday here's a download to our the release candidate which you can run and provide feedback if you'd like. It can be installed directly over top of your current Plex for Windows installation.

https://artifacts.plex.tv/plex-desktop-alpha/1.31.0.2237-fee1658d/windows/Plex-1.31.0.2237-fee1658d-x86_64.exe

**Comment by tartley** [comment]
@Jako4460 did the new release fix this issue?

**Comment by Jako4460** [comment]
> @Jako4460 did the new release fix this issue?

Hi
Unfortunatly the problem still persists. Once again i have played until the 'lag' happened, then disabled hardware decoding and played again till another 'lag' happned and closed the player. The log is attached.

[Plex.log](https://github.com/plexinc/plex-media-player/files/8104969/Plex.log)

**Comment by Jako4460** [comment]
> @Jako4460 did the new release fix this issue?

Seems like the latest update solved the issue. Thanks
