### ISSUE TITLE
Player does not handle remote control commands from clients that are not subscribed

### ISSUE THREAD

**Issue by DMarby** [plexinc/plex-media-player#199]
When attempting to control the PMP I noticed that it refuses to do playback commands from clients that are not subscribed, even tho the Remote Control Api spec in the wiki says that that "Players MUST accept and process commands received from unsubscribed controllers, even if they lack a commandID.", is this intentional?

This currently makes it impossible to control PMP through the plex media server, since the plex media server does not forward any of the /subscribe or /poll requests.

**Comment by tru** [comment]
Cc: @kayone

**Comment by kayone** [comment]
can you explain to me what your setup looks like and how I can re-create it here, which controller

>  makes it impossible to control PMP through the plex media server
can you explain what you mean by _control through the plex media server_, you mean controlling PMP using the desktop web UI?

**Comment by DMarby** [comment]
My setup right now consists of my own controller, a plex media server, and a plex media player client.
In the plex media server there is an api to forward commands to clients, such as http://media-server:port/system/players/<clientIp>/playback/playMedia.
However, the subscribe and poll url:s is not supported by that, and since the plex media player doesn't listen to playback commands from clients that are not subscribed, it is now impossible to control from outside the network without exposing the client itself. The reason for sending the commands through the server would be so that one only needs to expose the server to the outside world, and have it handle authentication.

**Comment by MikeOne** [comment]
Ping.

I'm having the same issue. With PHT it is possible to use the PMS as a proxy to control the player. This doesn't currently work for PMP. Also, direct control of the player is much more complicated if the player needs to be subscribed and is required to regularly sent the subscribe command (if I understand it correctly).

Any updates on this issue?

**Comment by elan** [comment]
I've raised the issue internally, sorry we lost track of it!

**Comment by DMarby** [comment]
Any updates on this?

**Comment by elan** [comment]
I'll ping again internally, thanks!

**Comment by elan** [comment]
Actually just found the issue. It was slated for completion mid-April, so I'm assuming it won't be too much longer now.

**Comment by tru** [comment]
I am pretty sure this is probably all the host's fault. I have it on my list to look into, but when I started to look at it there was not a easy fix here lot of logic that was depending on having the x-plex-target-identifier in a lookup table. This is an PMP implementation issue for sure, but still needs to retest the whole bamboozle again so I need to carve out time for doing that

**Comment by vanstinator** [comment]
Tracking this for CortanaPlex.

**Comment by MikeOne** [comment]
At least I have a custom controller to work now by controlling PMP directly with the API. The subscribing is a bit of a pain, however, simply calling the subscribe endpoint before any command seems to work fine.

**Comment by Petter-W** [comment]
I still can't get this working. Maybe somebody could update the remote control API documentation?

**Comment by LongChair** [comment]
@DMarby : i think this should be fixed now, can you confirm if we can close this ?

**Comment by DMarby** [comment]
@LongChair I am still seeing this behaviour with version `2.8.0.813-6e77dc0c` of Plex Media Player, all requests other than /subscribe or /poll just returns a 406 status-code for controllers that haven't subscribed.

**Comment by LongChair** [comment]
@markus101 : maybe we should rediscuss this, i’m not very familiar with this API

**Comment by ttshivers** [comment]
Is there any update on this issue?
