### ISSUE TITLE
Rewind / Fast-forward buttons does not work on Linux

### ISSUE THREAD

**Issue by jleroy** [plexinc/plex-media-player#244]
Using [packages I've build](https://forums.plex.tv/discussion/comment/1133645) for Fedora 23 x64, "rewind" and "fast-forward" buttons does not work. 
When I click on any of these buttons, the progress bar move and immediately go back to is previous position. The video blink but continue to play. 

The same fonctions works on my OS X computer using PMP 1.0.4 and the same Plex server, so I don't think it's a server-side problem.

This problem occurs on my Intel NUC, on a VMware VM and has also been reported by [another user](https://forums.plex.tv/discussion/comment/1133645/#Comment_1133645).

I have not made any changes on PMP source code when building packages.

Log file: [plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/140024/plexmediaplayer.log.txt)
Screencast: https://1fichier.com/?scg3cb3q4b (/!\ 76 M)

**Comment by wm4** [comment]
```2016-02-22 02:45:29 [ ERROR ] PlayerComponent.cpp @ 432 - main: Option seek: invalid time: '75.16' 
2016-02-22 02:45:29 [ ERROR ] PlayerComponent.cpp @ 432 - main: Command seek: argument 1 can't be parsed: option could not be parsed. ```
Something apparently overwrites the locale. Normally this shouldn't happen. Sounds like it'd be rather hard to find out what does it.

**Comment by tru** [comment]
I thought we forced the locale in the main function?

**Comment by wm4** [comment]
Yes, we do. But something could change it back. It sometimes happens with badly written plugins and such. (But I can't think of anything plugin-like we'd load.)

**Comment by jleroy** [comment]
I don't think it's related but `QLocale::system()` is called in https://github.com/plexinc/plex-media-player/blob/master/src/input/InputRoku.cpp#L178

**Comment by tru** [comment]
That should only poll the current locale and it's also not in 1.0.x series it was added after that in 1.1.0

**Comment by mklooss** [comment]
can confirm this issue on an Debian Jessie amd64 based on commit 48b5f41c613466aaae9ef19f8499d15a1449a4c9

**Comment by tru** [comment]
a update to the web-client broke the locale? @wm4 does that make any sense?

**Comment by wm4** [comment]
No. But I think it's not supposed to be the result of a bisect.

**Comment by mdesdin** [comment]
It is happening to me on Ubuntu 15.10 Desktop, but not on Ubuntu 14.04 Server, using qt-opensource-linux-x64-5.6.0_360.run installer on both

**Comment by mdesdin** [comment]
Is there any temporary solution to force the right locale for this not to happen?

**Comment by tru** [comment]
Must be something that resets the locale under us. @wm4 can we make this not depend on the locale in some clever way?

**Comment by mdesdin** [comment]
I have compared LC_* vars set in Ubuntu 15.10 against Ubuntu 14.04 and in 14.04 these are only 2 (ALL and CTYPE), but in 15.10 these are too many... And too many of them are not en_US, because I am not there and my keyboard is also not US. So my simple fix is to keep the defaults in 15.10 as simple as in 14.04 and all set to en_US.UTF8.

I also suppose the var responsible for the problem is LC_NUMERIC. Is Plex locale aware at all?

(I will play with these vars another day and check for NUMERIC or any other var that might be responsible, for now my problem is fixed and it is later around here...)

**Comment by wm4** [comment]
Yes, it's LC_NUMERIC. We unset it, but something sets it later again while the process is running. Which is very broken behavior and not done by us. I'm not sure what does that.

> @wm4 can we make this not depend on the locale in some clever way?

Short of writing our own libc replacements, no,

**Comment by wm4** [comment]
Actually, I'm not sure whether the commit above works as intended, as I haven't been able to reproduce the circumstances. But it's worth a try.

**Comment by mdesdin** [comment]
In my case, Ubuntu's case, it seems like the trick that should fix it, is not to unset it, but to set it to a value that Plex can work with, lets say en_US, so whenever the re-init of this value happens, this value is already set and is hopefully not overridden.

**Comment by mdesdin** [comment]
You last commit seems to have fixed the seek_ actions, but not the continue playing where left, this gets reset to the start... and like you said, not sure this is not failing elsewhere...

**Comment by wm4** [comment]
Then it works, but yeah, it doesn't fix everything.

Point is, this shouldn't happen in the first place.

All I could suggest is running PMP in gdb, and setting a breakpoint on setlocale(). But since setlocale() can also be used to _query_ the locale, there will be many harmless calls, and it's going to be pretty annoying.

**Comment by mdesdin** [comment]
exactly, I remember my old times when I had to do this, it is really annoying, but now that I got my temporary solution and all is working as expected so far, I will be able to spend some time helping with this...

**Comment by jleroy** [comment]
Seems to be fixed in v1.1.2.

**Comment by wm4** [comment]
Indeed, we've applied a hardcore hack that should have fixed this. (We force the environment variables to C locale at startup.)
