### ISSUE TITLE
Cannot get PMP master (1.2.1.dev-a42bd772) window to show up in Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by mdesdin** [plexinc/plex-media-player#470]
This is the log
[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/639443/plexmediaplayer.log.txt)

This one is compiled against Qt 5.8.0-rc, but the same happens with Qt 5.7.1 and Qt 5.7.0. Any clue from the log?

The portion of the log that seems to be the problem to me are the entries that list a QXcbConnection: XCB error.

PMP master + Qt 5.7.1 on Ubuntu 16 is OK, does not exhibit such error.

Right now I am back on tags/v1.1.7.442-5d0c3c70 with Qt 5.7.1 for Ubuntu 14, this combination is OK.

**Comment by tru** [comment]
Not seeing anything strange in the logs there. We have tried to get 5.8.0 to work - but there are some major issues with it and PMP right now. 5.7.1 should be fine though. So you say the window doesn't even show?

**Comment by wm4** [comment]
Works for me on Debian unstable with a Qt 5.7.1 snapshot too.

**Comment by mdesdin** [comment]
yes, the window doesn't even show, it runs in the background up to the point in the log and there is stays, it never shows, nothing, after a while i kill the process.
here are the logs with Qt 5.7.1, a clean install, with clean settings.
PMP log:
[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/639560/plexmediaplayer.log.txt)
PMP runtime output in the terminal:
[pmp-run-out.txt](https://github.com/plexinc/plex-media-player/files/639558/pmp-run-out.txt)
PMP compile and install output:
[pmp-compile-install-out.txt](https://github.com/plexinc/plex-media-player/files/639559/pmp-compile-install-out.txt)

**Comment by mdesdin** [comment]
@wm4 it does work for me too, but as with you it is on a different system: ubuntu 16 and Qt571. my problem is with ubuntu 14 lts.

**Comment by edouardl** [comment]
@mdesdin I have the same issue on Ubuntu 16.04.1 LTS (fresh install) with Qt5.71, it never show up.
In my case I was obliged to execute the CMake command for plexmediaplayer twice, the first time it's end with errors ([CMakeError.txt](https://github.com/plexinc/plex-media-player/files/640789/cmake-error.txt) ), the second it passed.
Had you the same behaviour ?

**Comment by mdesdin** [comment]
@edouardl nope, on ubuntu 16.tls all compiles fine and also works fine, and on ubuntu 14.tls the compilation is also fine, but it never shows up.
i just checked your cmake errors and this is something i never had in any of both ubuntus, i am compiling pmp for months already.
what about previous versions of pmp, did they work for you?
now that pmp compiled, i would suggest you post pmp log, this helps understand if you are facing the same problem.
regarding cmake, which version are you nunning? mine is cmake version 3.5.1

**Comment by edouardl** [comment]
Actually I tried several times to install pmp, with ubuntu fresh install every time. On time pmp show up once, but I never do it again. Unfortunately I didn't keep the log, since it never show up.

I didn't try others versions yet. I'm running cmake 3.5.1.
[plexmediaplayer.txt](https://github.com/plexinc/plex-media-player/files/641457/plexmediaplayer.txt)
[pmp-run-output.txt](https://github.com/plexinc/plex-media-player/files/641465/pmp-run-output.txt)

**Comment by tru** [comment]
Ah here is the problem:
```
2016-12-08 23:32:06 [ DEBUG ] KonvergoWindow.cpp @ 236 - Restoring geo: QRect(1073741184,1073741464 1280x720) 
2016-12-08 23:32:06 [ DEBUG ] KonvergoWindow.cpp @ 236 - Restoring geo: QRect(1073741184,1073741464 1280x720) 
```

Those X/Y coordinates is probably waaaaaay outside of your screen.

Open storage.json and edit the `geometry` section in there. Next up: figure out why it saves bonkers values in there.

**Comment by mdesdin** [comment]
@tru thanks! will do so when back at home and report back...

**Comment by mdesdin** [comment]
@tru, it might be something else. my first test was only fixing the x and y parameters in storage.json, with the same result, pmp window does not show up. this initial storage.json was missing a lot of vars, so i decided to use a backup of storage.json from v1.1.7, but with the same result... this is the new log.
[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/642518/plexmediaplayer.log.txt)

**Comment by kalle-del-haye** [comment]
I had the same problem on Ubuntu 16.04 and QT 5.7.0 - black screen when starting PMP.

Starting PMP with the option `--scale-factor=1` solved the issue for me.

@edouardl To be able to build PMP successfully, I have to used the little trick from the README:
>locate Qt5CoreConfigExtras.cmake of your Qt build/installation
>comment set_property(TARGET Qt5::Core PROPERTY INTERFACE_COMPILE_FEATURES cxx_decltype) with #

**Comment by mdesdin** [comment]
@kalle-del-haye thanks a lot, so far so good, --scale-factor=1 did the trick, now it is working on my ubuntu 14.lts + qt 5.7.1

**Comment by edouardl** [comment]
@kalle-del-haye same for me, it's working now. Thank's a lot !

**Comment by mdesdin** [comment]
@tru is this issue considered fixed with the --scale-factor=1 option? i could close it in this case... (too many open issues around)

**Comment by miketweaver** [comment]
I've been having this same issue myself, but on Gentoo. I was jumping from pmp 1.1.3 to the latest 1.2.1. From qt 5.6 to 5.7.1

I built qt and pmp and everything seemed fine, though when starting the x11 server with the application, everything was black. I assumed there was something wrong. It took me a pair of hours to find that --scale-factor=1 fixed my issue as well.

**Comment by tru** [comment]
I think we should find a better way to no break down. But it seems to be a Qt bug. We could possible work around it if not fixed in 5.8

**Comment by mdesdin** [comment]
It was not fixed with Qt5.8-rc. I will keep trying with coming versions.

**Comment by tru** [comment]
Does xpdyinfo report any dpi for you? It must be something with Qts dpi detection that goes wrong.

**Comment by mdesdin** [comment]
here is the output
[xdpyinfo.txt](https://github.com/plexinc/plex-media-player/files/656551/xdpyinfo.txt)

**Comment by father-mande** [comment]
Hi,

F.Y.I. ... I fall also in this problem ... on one platform not on the other
Build 1.2.0
same Ubuntu 14.04 based (same P.MP. delivery (by me))
on system based on Celeron J1900 ... all seems to work as expected
on system based on Celeron N3080 ... similar error ... PMP start but don't seems to display somethings on screen
on system based on AMD SOC RX-421BD (so IGP R series) ... all seems to work as expected ...

I have no idea if IGP or driver is the reason ... just to add my two cent to this question ...

Philippe.
I can't easily have more info ... because if I own the J1900 and the AMD QNAP's model ... I don't have the other series ... so linked to return from other users ... (I will search a test box to be more clear)

**Comment by LongChair** [comment]
This should be fixed now, closing.
