### ISSUE TITLE
Fail to launch with a segmentation fault

### ISSUE THREAD

**Issue by Aanok** [plexinc/plex-media-player#495]
On Debian 8, launching PMP fails on a Segmentation fault.

It used to run as long as I used the integrated graphics card, an ancient Geforce 6100. This started to happen as I switched to an AMD Radeon HD5450.

Here is the output of a gdb session:
```
Starting program: /usr/local/bin/plexmediaplayer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffde825700 (LWP 30094)]
[New Thread 0x7fffde024700 (LWP 30095)]
[New Thread 0x7fffdd823700 (LWP 30096)]
[New Thread 0x7fffd584d700 (LWP 30097)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde024700 (LWP 30095)]
0x00007fffdc9a0a20 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so

```
[lsmod.txt](https://github.com/plexinc/plex-media-player/files/687174/lsmod.txt)
[modinfo radeon.txt](https://github.com/plexinc/plex-media-player/files/687175/modinfo.radeon.txt)
[glxinfo.txt](https://github.com/plexinc/plex-media-player/files/687199/glxinfo.txt)

Please do tell if you need more information on my setup.

**Comment by tru** [comment]
Must be a driver issue. Does any Qt programs work?

**Comment by Aanok** [comment]
Yes, everything else works normally.

**Comment by tru** [comment]
Since it crashes inside r600_dri.so I am not sure what we can do... it must be something with the ATI supplied code.

**Comment by Aanok** [comment]
Indeed it turned out my system had issues. I ended up formatting and recompiling, now PMP runs without errors. However, it launches to a black screen and is completely unresponsive. This happens with both open source and proprietary drivers.

I should probably mention I'm not running it in a desktop environment, but with an "exec plexmediaplayer" as last line of a .xinitrc invoked with startx. I've also tried running it in Openbox, though, with same results.

Looking at the [plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/689791/plexmediaplayer.log.txt) I see an `2017-01-06 12:40:21 [ ERROR ] DisplayManager.cpp @ 46 - DisplayManager : unable to retrieve main display` that might be a clue, but it also looks like PMP was able to identify the display correctly before. Also there are those `QXcbConnection` errors I'm not too sure about, although some googling seems to suggest they could be safely ignored.

**Comment by wm4** [comment]
The DisplayManager error can be ignored. But the XCB errors must be the cause for this. Before trying anything else, can you try to wipe your PMP config files?

**Comment by Aanok** [comment]
Deleted ~/.local/share/plexmediaplayer/, ~/.cache/plexmediaplayer, ~/.config/plex.tv (it should be everything, right?), error is still there: 
[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/694065/plexmediaplayer.log.txt)

**Comment by jturcotte** [comment]
The XCreateWindow doc says that you can get a BadValue for:
> Some numeric value falls outside the range of values accepted by the request. Unless a specific range is specified for an argument, the full range defined by the argument's type is accepted. Any argument defined as a set of alternatives can generate this error.

And I see huge values for the window geometry in the log (that might get passed to CreateWindow):
```
2017-01-09 17:43:01 [ DEBUG ] KonvergoWindow.cpp @ 237 - Restoring geo: QRect(1073741184,1073741464 1280x720) 
2017-01-09 17:43:01 [ DEBUG ] KonvergoWindow.cpp @ 237 - Restoring geo: QRect(1073741184,1073741464 1280x720) 
```

This could be the reason.

**Comment by wm4** [comment]
I overlooked this. Strange that it would restore geometry even though the config was wiped?

**Comment by wm4** [comment]
I couldn't reproduce this. What window manager are you using?

Also please try to update and rebuild from git. Post a new log.

**Comment by Aanok** [comment]
Updated and rebuilt, still nothing.
I'd rather not use any WM at all, but the following log was generated under Openbox, on erased configs. As far as I can tell a WM doesn't make any difference.

Outlandish geometry values are still there, unfortunately.

[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/702742/plexmediaplayer.log.txt)

**Comment by wm4** [comment]
Made a big oversight, which means my commit did nothing but add logging. I fixed it now. Please pull and retry. Meanwhile I'll see if I can get openbox running.

**Comment by wm4** [comment]
OK, running OpenBox was simple. Couldn't reproduce this problem.

Running out of ideas. Where did you get your Qt build and what version is it exactly?

**Comment by Aanok** [comment]
I downloaded and ran the online installer from qt.io. It's version 5.7.1.

I rebuilt, but it looks like the geometry still gets set wrong.
[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/703835/plexmediaplayer.log.txt)

**Comment by wm4** [comment]
Still can't reproduce.

Please update from git again, I added more logging. Depending on the results, I might add a dumb workaround to fix it the gross way.

**Comment by Aanok** [comment]
It's still there. Looks like it's having issues detecting the display and overflowing .
```
2017-01-13 12:24:30 [ ERROR ] DisplayManager.cpp @ 46 - DisplayManager : unable to retrieve main display 
2017-01-13 12:24:30 [ INFO  ] DisplayComponent.cpp @ 75 - Screen QScreen(0x23ff500, name="HDMI-0") with geometry QRect(0,0 -2147483648x-2147483648)
```
[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/704165/plexmediaplayer.log.txt)

**Comment by wm4** [comment]
Pushed another hack, no idea if that helps.

**Comment by chadberg** [comment]
Came to leave a similar comment. I just turned on PRIME to render with the ATI Radeon instead of the Intel chip, and started seeing this segfault bahavior. I'm using XFCE, but I don't think the DE/WM matters. Here's my gdb output:

> Reading symbols from plexmediaplayer...(no debugging symbols found)...done.
> (gdb) r
> Starting program: /usr/bin/plexmediaplayer 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/usr/lib/libthread_db.so.1".
> [New Thread 0x7fffc3228700 (LWP 18950)]
> [New Thread 0x7fffc2a27700 (LWP 18951)]
> [New Thread 0x7fffc2226700 (LWP 18952)]
> [New Thread 0x7fffb90d1700 (LWP 18953)]
> [New Thread 0x7fffb88d0700 (LWP 18954)]
> [New Thread 0x7fffb3fff700 (LWP 18955)]
> [New Thread 0x7fffb37fe700 (LWP 18956)]
> [New Thread 0x7fffb2ffd700 (LWP 18957)]
> 
> Thread 3 "mpv/vo" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffc2a27700 (LWP 18951)]
> 0x00007fffee552255 in ____strtoull_l_internal () from /usr/lib/libc.so.6
>

**Comment by wm4** [comment]
@chadberg that looks like a different issue.

**Comment by chadberg** [comment]
Ok, I'll file separately.

**Comment by wm4** [comment]
What if you start it with `--scale-factor=1` on the command line? Maybe this is similar to this issue:

https://forums.plex.tv/discussion/comment/1343846/#Comment_1343846

**Comment by Aanok** [comment]
That did it! PMP launches and works and the log is free of errors. Thank you very much.

[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/710321/plexmediaplayer.log.txt)

**Comment by wm4** [comment]
We need to further analyze this issue so we can fix it without requiring the user to workaround manually.

Can you post the output of `xdpyinfo`?

**Comment by Aanok** [comment]
Of course.
[xdpy.txt](https://github.com/plexinc/plex-media-player/files/710411/xdpy.txt)

**Comment by jturcotte** [comment]
Could you also post the output of `xrandr --verbose`? :)

**Comment by Aanok** [comment]
There you go.
[xrandr.txt](https://github.com/plexinc/plex-media-player/files/710778/xrandr.txt)

**Comment by wm4** [comment]
Is your monitor really `1600mm x 900mm`?

**Comment by Aanok** [comment]
Yes, it's a living room machine connected to a TV set.

**Comment by Aanok** [comment]
No. While it is a TV set, it's more like 70cm x 40cm.

**Comment by wm4** [comment]
xrandr/your TV reports these too large sizes, which is causing an overflow.

**Comment by tru** [comment]
We are looking into a fix.

**Comment by jturcotte** [comment]
Prospective fix for qtbase: https://codereview.qt-project.org/182622
I'm pretty sure that this should fix the issue, otherwise setting the `QT_AUTO_SCREEN_SCALE_FACTOR=0` environment variable should also be a reliably workaround.

**Comment by jturcotte** [comment]
The Qt bug was already reported at https://bugreports.qt.io/browse/QTBUG-56140
The fix should go in Qt 5.8.1 (if they don't skip that release) and 5.9.0, but can probably be back-ported easily locally.

**Comment by Aanok** [comment]
I can confirm that setting `QT_AUTO_SCREEN_SCALE_FACTOR=0` instead of passing `--scale-factor=1` works as well.

**Comment by LongChair** [comment]
Closing this as it should be fixed now.
