### ISSUE TITLE
v2.4.1 - On deck doesn't refresh after playing an episode from there

### ISSUE THREAD

**Issue by enchained** [plexinc/plex-media-player#665]
Steps to reproduce:

1. Press play while one of on deck episodes is highlighted (preferably one that won't have a next play screen cause it's the last episode).
2. Watch the episode until the end and let the screen go back to dashboard automatically.

Result:
The episode is still on deck, doesn't have an orange corner now, will disappear only after library switching back and forth (some sort of refreshing).

Expected result:
The episode should disappear from on deck right after playing, as long as it was finished and doesn't have an orange corner.

**Comment by LongChair** [comment]
Hi,

Could you please check if the issue is still there in 2.8.0 ?

**Comment by enchained** [comment]
@LongChair Hi. The issue is still there in 2.8.0. Can still reproduce it with watching the last episode of some show on deck. If the episode not the last and I specifically go BACK from the "playing next" screen - the dashboard refreshes. But if there isn't any more episodes, and no "playing next" screen, the dashboard does not refresh when you return to it automatically. I have to switch libraries for it to refresh.

Also, it would be nice if it did autorefresh on new items added, like the web version does. Right now I can't see new additions if the plex was on and idle, until I switch libraries back and forth. If there's no adequate way to trigger refresh on every new addition, refreshing after return from the screensaver could be also fine.

**Comment by LongChair** [comment]
@markus101 : anything we could do there ?

**Comment by markus101** [comment]
Yeah I think we have a few things we could so here. I've filed an internal issue for it.

**Comment by LongChair** [comment]
@markus101 : internal issue being closed, should we close this ?

**Comment by bensmithy123** [comment]
Still happening in server 1.12.3.4973 running web version 3.41.2 -  unsure how to view internal issues so sorry if this becomes irrelevant in next patch or something?

I watch from on deck on plex web app then after watching when I close the video the on deck stays the same until I refresh(f5) or move pages(click on a library then back to home icon etc)

Thanks

**Comment by markus101** [comment]
@LongChair the internal issue is still open, only the likely dupe issue in this repo was closed.

@bensmithy123 you can't view internal issues, it's part of the closed source web app. I can't say when it'll be fixed, but will say it won't be this next release.

**Comment by mseeley** [comment]
Internal issue was fixed in Apr, sweeping up dusty issues.

**Comment by bensmithy123** [comment]
I am still having this issue
Server Version 1.14.0.5470
Web client Version 3.77.2

**Comment by bensmithy123** [comment]
@mseeley please re check this

**Comment by mseeley** [comment]
HI @bensmithy123 would you mind providing the steps you were using to reproduce? I need to also know which version of Plex Media Player you were using and if you were in the TV or Desktop layout.

**Comment by bensmithy123** [comment]
@mseeley Thanks for the quick response. Exact same as before this was marked as solved, press play from the deck, let it finish, when I close the player the deck does not update to the next episode until I either refresh or move to a different page then hit home again. The tv app works fine (lg webos3) and does this as expected. I assume the web app is in desktop mode, it is running on chrome, web link is app.plex.tv/desktop#.

I am running plex through an unraid docker (https://hub.docker.com/r/plexinc/pms-docker/) which is on the beta/plexpass branch. I believe this is the official docker app?

It might be worth mentioning that I had the exact same issue on the windows server which I transitioned from a couple of months ago so I assume they are relatively the same build.

**Comment by mseeley** [comment]
Ah, thanks @bensmithy123. It sounds like you're using the hosted web app; yep 3.77.2 is the latest deployed revision. The docker you mentioned is our official docker; looks like the last update was just over a week ago.

Sometimes our apps get confusing. A variation of the hosted app is bundled with Plex Media Server and another variation is bundled with Plex Media Player. This repo specifically is for Plex Media Player. Although! The bug you described would be reproducible an any variation of the hosted web app. The hosted version is always the newest. If we cannot reproduce there then a fix will make it to Plex Media Server and Plex Media Player in a couple weeks.

I don't doubt there's a bug but I'll need some help to reproduce it. I tried the following steps unsuccessfully:

1. Visit https://app.plex.tv/desktop
1. Press the Play icon when hovering over an episode in the On Deck list shown on the home screen.
1. Seek to the end of the movie.
1. Stop playback and return to the home screen.
1. The next episode displays on the home screen.

![kapture 2018-12-04 at 13 05 01](https://user-images.githubusercontent.com/30019/49479253-6e3ee100-f7c6-11e8-8909-3d555ebee7f3.gif)

1. Visit https://app.plex.tv/desktop
1. Mark all episodes of a season watched, except the last episode.
1. Press the Play icon when hovering over an episode in the On Deck list shown on the home screen.
1. Seek to the end of the movie.
1. Stop playback and return to the home screen.
1. The On Deck list disappears from the home screen.

![kapture 2018-12-04 at 13 06 56](https://user-images.githubusercontent.com/30019/49479293-92022700-f7c6-11e8-9cb2-4d37bcd5e3d2.gif)

**Comment by bensmithy123** [comment]
@mseeley I have done a copy of the two you have done
1.
![1](https://user-images.githubusercontent.com/38706600/49541589-1b028680-f8cb-11e8-8c08-88ff8aac1f36.gif)

2.
![2](https://user-images.githubusercontent.com/38706600/49541606-2a81cf80-f8cb-11e8-99b8-d1497f979477.gif)

As you can see mine does not update when I close the player, any thoughts?? thanks

**Comment by mseeley** [comment]
Thanks for the screencaps! I'm assuming this was against our hosted app like you mentioned above. With this in mind there's clearly a... glitch in the matrix.

My tests were run against a local Plex Media Server (PMS) build that's a bit newer than 1.14.0.5470. I'll install an older version and review PMS changes for any On Deck fix.

After playback completes to do you see any error logs in [Chrome's error console](https://developers.google.com/web/tools/chrome-devtools/console/)? If the error console feels hard to use you can also look at the end of the logs [in our app](https://support.plex.tv/articles/201611836-plex-web-app-logs/) after playback finishes.

**Comment by bensmithy123** [comment]
@mseeley Hopefully the attached logs can be of use..
[plex debug log.txt](https://github.com/plexinc/plex-media-player/files/2650625/plex.debug.log.txt)
[chrome app.plex.tv-1544043420075.log](https://github.com/plexinc/plex-media-player/files/2650626/chrome.app.plex.tv-1544043420075.log)

the chrome one looks a bit more useful, see below screenshot which makes it clearer
![image](https://user-images.githubusercontent.com/38706600/49543973-864f5700-f8d1-11e8-8570-6ff4bd458ba3.png)
 
Sounds like the hosted app is trying to force an update when I close the player but fails to find the component it is looking for? just a guess..

I have just forced an update that pulled the web client to 3.79.0 from 3.77.2 but server version appeared not to change, still go the same errors as above.  cheers again

**Comment by bensmithy123** [comment]
@mseeley Hi Matt, any updates on this please? Still happening on the latest update.

**Comment by beljim** [comment]
Any update? This has been happening to me for years. On deck for PC refuses to refresh after watching a file.

**Comment by mluerig** [comment]
I am having this issue on all platforms, including windows and LG web os

Server Version#: 1.21.3.4014
Player Version#: 8.12.4.22902

**Comment by OttoKerner** [comment]
This version number is from a Plex _Android_ client. 
This repository is about Plex Media Player and Plex for Windows/Mac.

**Comment by mluerig** [comment]
right - sorry!

I am using the browser based web client (app.plex.tv Version 4.52.1), but I could give the desktop client a try as well

**Comment by GavinHellyer** [comment]
Having this issue on latest Nvidia Shield TV Pro version of the app, since the new ui was implemented
