### ISSUE TITLE
Settings not accessible when in Full screen mode 

### ISSUE THREAD

**Issue by PartTheSeas** [plexinc/plex-media-player#715]
**PMS Version:** 1.13.0.5003
**PMP Version**: Currently 2.10.0 (but also past versions)
**Platform:** Win10

**Steps to reproduce**

1. Start Plex in Web view and full screen
2. Minimize Plex to a window
3. Start PMP in TV Mode
4. Play any music file (Audio) in TV mode, let it play in the background and go to home screen or any other library than the actual music player
5. Click on your username and icon for the context menu to open
6. Click on "Settings"

**Current behavior**

1. Settings popping up briefly, then instantly closes and is not accessible

**Expected behavior**

1. Enter settings

_Note: If the music is stopped and not running anymore, settings can be entered afterwards_

[Plex Media Server Logs_2018-05-02_02-27-20.zip](https://github.com/plexinc/plex-media-player/files/1965566/Plex.Media.Server.Logs_2018-05-02_02-27-20.zip)

**Comment by PartTheSeas** [comment]
Wow this was quick! Awesome! I could provide you with a small video also, if you wish. I'm new to GitHub and idk how things work over here

**Comment by LongChair** [comment]
PlexMediaServer logs won't help much :)
And as i said earlier i haven't been able to reproduce your issue.
Waiting on a few others to confirm if they can repoduce it. If not then i guess you might have something wrong on your setup...

**Comment by dan-the-man-nz** [comment]
i tried this on PMP 2.10.0.849/Win10, played a audio track, went back to the home screen with the music still playing, i was able to access and change settings fine

**Comment by LongChair** [comment]
@PartTheSeas : you might want to make sure you're running the latest build.

**Comment by PartTheSeas** [comment]
@dan-the-man-nz Okay thank you very much for taking the time. As @LongChair noted it really might be something wrong with my setup, even though I don't have any idea what that might be. Also @LongChair I'm running the very latest builds of all components

**Comment by LongChair** [comment]
maybe a video then could be helpful to see the issue in case we reproduce it wrong.
Although not sure what we can do if we can't reproduce it

**Comment by OttoKerner** [comment]
I cannot reproduce on Windows. I see the settings alright while music is playing in the background.
Are you using a particularly small window size or did you apply scaling at the system level?

**Comment by LongChair** [comment]
@PartTheSeas : can you make a check with this build eventually ? 

https://www.dropbox.com/s/w7neafa3ymv86mk/PlexMediaPlayer-2.10.0.854-c1633f57-windows-x64.exe?dl=0

**Comment by PartTheSeas** [comment]
@LongChair Can't believe it, but on this build it works like a charm! <3 Could you tell me what the problem was or could've been?

**Comment by LongChair** [comment]
we have made a few fixes to angle / OpenGL :p

Probably hardware dependent which is why other people wouldn't have it, bu ti'm glad it works ok for you now.

be patient until that fix is merged :)

**Comment by PartTheSeas** [comment]
That's just awesome :) Thank you very much for your efforts! While we're at it: Could you maybe help me on another problem? (Which probably isn't fixed that easy)
Nobody found a solution for it, but I believe I'm not the only one. It's located here:

https://forums.plex.tv/discussion/290334/does-somebody-else-have-cursor-remains-on-plex-media-player#latest

If you could have a look into that I'd be so grateful, since this is boggling my mind forever already

**Comment by LongChair** [comment]
Cursors behavior is soon in my list.
There are a bunch of other issues already in this repo mentionning it.
Feel free to subscribe to those, when i start this, i’ll post test builds there :)

**Comment by PartTheSeas** [comment]
Ohhh great!!! If this would be fixed any day I'd be so happy :D It's really annoying to put the cursor off of the screen anytime you watch something :D I'll definitely subscribe to that! Can't wait <3

So thank you again very, very much. Made my day :)<3

**Comment by LongChair** [comment]
PR addressing this issue was merged.

**Comment by RSully** [comment]
Just want to make note that I experienced the original issue described here as well. I had to manually kill the 'now playing' item from the server's web UI as I couldn't figure out how to stop it from the player itself.

re:

> Probably hardware dependent which is why other people wouldn't have it [...]

@PartTheSeas what hardware are you using?

**Comment by PartTheSeas** [comment]
@RSully Oh good to know that I'm not the only one :) I'm using an Asus machine with a GeForce GTX1050 2GB, 16GB DDR4 RAM and an Intel core i5-7400 on 2 LG monitors and an old SEG monitor
